const Data = [
    {
        id: 1,
        Company : 'ABCD',
        City : 'XYZ',
        Technology : 'Developer',
        Mobile : '0987654321',
        Email : 'abcd@gmail.com',
        Budget : 'Low budget',
        Status : 'Active',
    },
    {
        id: 2,
        Company : 'ABCD',
        City : 'XYZ',
        Technology : 'Developer',
        Mobile : '0987654321',
        Email : 'abcd@gmail.com',
        Budget : 'Low budget',
        Status : 'Active',
    },
    {
        id: 3,
        Company : 'ABCD',
        City : 'XYZ',
        Technology : 'Developer',
        Mobile : '0987654321',
        Email : 'abcd@gmail.com',
        Budget : 'Low budget',
        Status : 'Active',
    },
    {
        id: 4,
        Company : 'ABCD',
        City : 'XYZ',
        Technology : 'Developer',
        Mobile : '0987654321',
        Email : 'abcd@gmail.com',
        Budget : 'Low budget',
        Status : 'Active',
    },
    {
        id: 5,
        Company : 'ABCD',
        City : 'XYZ',
        Technology : 'Developer',
        Mobile : '0987654321',
        Email : 'abcd@gmail.com',
        Budget : 'Low budget',
        Status : 'Active',
    },
    {
        id: 6,
        Company : 'ABCD',
        City : 'XYZ',
        Technology : 'Developer',
        Mobile : '0987654321',
        Email : 'abcd@gmail.com',
        Budget : 'Low budget',
        Status : 'Active',
    },
    {
        id: 7,
        Company : 'ABCD',
        City : 'XYZ',
        Technology : 'Developer',
        Mobile : '0987654321',
        Email : 'abcd@gmail.com',
        Budget : 'Low budget',
        Status : 'Active',
    },
    {
        id: 8,
        Company : 'ABCD',
        City : 'XYZ',
        Technology : 'Developer',
        Mobile : '0987654321',
        Email : 'abcd@gmail.com',
        Budget : 'Low budget',
        Status : 'Active',
    },
    {
        id: 9,
        Company : 'ABCD',
        City : 'XYZ',
        Technology : 'Developer',
        Mobile : '0987654321',
        Email : 'abcd@gmail.com',
        Budget : 'Low budget',
        Status : 'Active',
    },
]

export default Data;